### ISSUE TITLE
Frontend: Scatter plot: Horizontal and vertical axes scale individually with window

### ISSUE THREAD

**Issue by chr5tphr** [virelay/virelay#14]
- When rescaling the browser window, the distribution of the points is scaled for the axis that  was resized, even when there is enough free space for the points to fit.
- E.g. when resizing the horizontal axis to a smaller size, the point cloud will become a vertical line.

<details>
  <summary>Wide Window</summary>
  
  ![image](https://user-images.githubusercontent.com/15217558/159765972-0dca27d9-d3ee-452f-bcec-7c607e3ec961.png)

</details>

<details>
  <summary>Narrow Window</summary>
  
  ![image](https://user-images.githubusercontent.com/15217558/159766129-2277d99c-3b6f-4164-a9b6-466fc3994f9a.png)
</details>

**Comment by lecode-official** [comment]
I have known about this issue and have already tried to fix it. But I got stuck and could not find a good solution. I cannot remember what the problem was, so I will have a look at it again.

**Comment by lecode-official** [comment]
I believe this problem was already fixed in 35232a4af4569169c27f805db3b7977abbf89086, because we no longer change the aspect ratio when the window size changes, but we update the top, left, right, and bottom of the orthographic camera in such a way, that the center of the camera remains the same.
