### ISSUE TITLE
Frontend: Image preview: Too large in vertically small window

### ISSUE THREAD

**Issue by chr5tphr** [virelay/virelay#16]
- When the browser image does not offer much space on the vertical axis, the images the majority of the vertical space.
- We could have the images resize to a minimal size when they cover a large fraction of the vertical space.

<details>
  <summary>Screenshot</summary>

  ![image](https://user-images.githubusercontent.com/15217558/159767513-4d4be87e-eeba-4296-8c51-c34f58e867bc.png)
</details>

**Comment by lecode-official** [comment]
Good point, we could specify different sizes for the different CSS breakpoints. I will have a look at it.

**Comment by lecode-official** [comment]
the height of the selected attributions pane is now responsive. When the height of the window decreases below 1080px, the height is decreased from 250px to 200px, and when the height of the
window goes below 720px, the height is decreased to 150px.
