### ISSUE TITLE
Fork request

### ISSUE THREAD

**Issue by oz-mishli** [virelay/virelay#32]
Hi, 

I'm an MSc student finishing my thesis, and I'd like to contribute my version of Virelay to the repo. My thesis discusses the detection and mitigation of the clever Hans phenomenon in univariate time series datasets. Thus, this code version includes adaptations for the convenient visualization and analysis of univariate time series in Virelay. I'd like to refer to this fork as part of my thesis and contribute this code to the public. In addition, my work quotes all relevant papers by Lapuschkin, Andres et. al and it is expected to be published shortly. 

Looking forward to your confirmation to fork.

Thanks,
Oz

**Comment by chr5tphr** [comment]
Hey Oz,

feel free to publish your fork!
Of course, it would be super cool if we could prepare it such that we can merge your fork back into the base repo, but no pressure!
As a side-note, be aware that your fork must also be published under the AGPL3+ if you publish the code in a separate repo.

**Comment by lecode-official** [comment]
I guess, this issue can be closed. @oz-mishli, if you publish any changes that would be interesting for the upstream repository, we would be happy if you could create a pull request. We wish you all the best for your thesis.
